create extension if not exists pg_trgm;

create table project (
    id             bigint generated by default as identity primary key,
    name           varchar(200) not null,
    source_type    varchar(20)  not null,
    source_uri     text,
    local_path     text         not null,
    branch         varchar(200),
    last_commit    varchar(64),
    status         varchar(20)  not null,
    status_message text,
    created_at     timestamptz  not null,
    updated_at     timestamptz  not null
);

create table analysis_run (
    id            bigint generated by default as identity primary key,
    project_id    bigint      not null references project (id) on delete cascade,
    mode          varchar(20) not null,
    status        varchar(20) not null,
    commit_hash   varchar(64),
    files_total   int         not null default 0,
    files_parsed  int         not null default 0,
    files_deleted int         not null default 0,
    entities      int         not null default 0,
    edges         int         not null default 0,
    duration_ms   bigint,
    error         text,
    started_at    timestamptz not null,
    finished_at   timestamptz
);
create index idx_run_project on analysis_run (project_id, started_at desc);

create sequence source_file_seq increment by 50;
create table source_file (
    id           bigint primary key,
    project_id   bigint       not null references project (id) on delete cascade,
    path         text         not null,
    module       varchar(300) not null,
    package_name varchar(500),
    sha256       varchar(64)  not null,
    loc          int          not null default 0,
    test         boolean      not null default false,
    parse_error  text,
    unique (project_id, path)
);

create sequence code_entity_seq increment by 50;
create table code_entity (
    id             bigint primary key,
    project_id     bigint       not null references project (id) on delete cascade,
    file_id        bigint       not null references source_file (id) on delete cascade,
    parent_id      bigint references code_entity (id) on delete cascade,
    kind           varchar(20)  not null,
    name           varchar(500) not null,
    qualified_name text         not null,
    package_name   varchar(500),
    signature      text,
    visibility     varchar(10),
    modifiers      varchar(200),
    annotations    text,
    stereotype     varchar(20),
    http_method    varchar(10),
    http_path      text,
    start_line     int,
    end_line       int,
    complexity     int          not null default 1,
    unique (project_id, qualified_name)
);
create index idx_entity_file on code_entity (file_id);
create index idx_entity_parent on code_entity (parent_id);
create index idx_entity_name_trgm on code_entity using gin (lower(name) gin_trgm_ops);

create table dependency_edge (
    id         bigint generated by default as identity primary key,
    project_id bigint      not null references project (id) on delete cascade,
    source_id  bigint      not null references code_entity (id) on delete cascade,
    target_id  bigint      not null references code_entity (id) on delete cascade,
    type       varchar(20) not null,
    weight     int         not null default 1,
    file_id    bigint      not null references source_file (id) on delete cascade,
    unique (source_id, target_id, type)
);
create index idx_edge_project on dependency_edge (project_id);
create index idx_edge_target on dependency_edge (target_id);
create index idx_edge_file on dependency_edge (file_id);

create table entity_metric (
    entity_id    bigint primary key references code_entity (id) on delete cascade,
    project_id   bigint           not null references project (id) on delete cascade,
    fan_in       int              not null,
    fan_out      int              not null,
    dependents   int              not null,
    dependencies int              not null,
    depth        int              not null,
    complexity   int              not null,
    risk_score   double precision not null
);
create index idx_metric_risk on entity_metric (project_id, risk_score desc);

create table module_metric (
    id           bigint generated by default as identity primary key,
    project_id   bigint           not null references project (id) on delete cascade,
    level        varchar(10)      not null,
    name         varchar(500)     not null,
    entities     int              not null,
    afferent     int              not null,
    efferent     int              not null,
    instability  double precision not null,
    abstractness double precision not null,
    distance     double precision not null,
    unique (project_id, level, name)
);

create table report (
    id         bigint generated by default as identity primary key,
    project_id bigint      not null references project (id) on delete cascade,
    entity_id  bigint references code_entity (id) on delete set null,
    kind       varchar(20) not null,
    facts      jsonb       not null,
    summary    text,
    model      varchar(100),
    created_at timestamptz not null
);
create index idx_report_project on report (project_id, created_at desc);
