create table app_user (
    id            bigint generated by default as identity primary key,
    email         varchar(320) not null,
    name          varchar(100) not null,
    password_hash varchar(100) not null,
    created_at    timestamptz  not null
);
create unique index uq_user_email on app_user (lower(email));

alter table project add column owner_id bigint references app_user (id) on delete cascade;
create index idx_project_owner on project (owner_id, created_at desc);
